Repository sakeel-103/DFS-BFS-Graph-Travers, pull requests merged in 2024-10, with the labels that each got.

#5 Added Navbar functionality
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/main-index/main-index.component.html
Labels: gssoc-ext, hacktober'24, Level1

#6 Added description for algorithms as a card
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.css
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#8 Added custom graph creation feature
  src/app/app.module.ts
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, Level3

#15 Form aesthetic upgraded and clear feature implemented
  package-lock.json
  package.json
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.css
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted

#18 Update README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#20 Added express validator
  backend/server.js
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#21 fixed the explore button and improved the style of homepage.
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#22 Added instructions to use graph feature in readme
  README.md
  image-1.png
  image.png
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#24 Added scroll feature
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#25 Add automated greeting message when PR is opened
  .github/workflows/greetings.yml
  backend/.env
  backend/models/User.js
  backend/server.js
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#28 Correct server file name
  backend/package.json
Labels: gssoc-ext

#35 Send json response string after User is created in db
  backend/server.js
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#37 Add auth and signup validate middlewares
  backend/middlewares/authenticate.js
  backend/middlewares/validation.js
  backend/server.js
Labels: gssoc-ext, hacktoberfest-accepted, Level2

#42 Fix Login Functionality and Redirect Logic
  .gitignore
  src/app/components/login-page/login-page.component.html
  src/app/components/login-page/login-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted

#45 Add an environment variable to allow easier adjustments of hash password
  backend/server.js
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#47 Implement a graceful shutdown
  backend/server.js
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#49 Improve UI/UX Design for Graph Traversal Page
  src/app/components/main-index/main-index.component.css
  src/app/components/main-index/main-index.component.html
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#51 Make canvas scrollable and adjust height according to max depth of DFS
  src/app/components/dfs-page/dfs-page.component.css
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, Level2

#43 Made all the go back option and close option in login page
  src/app/components/login-page/login-page.component.html
  src/app/components/login-page/login-page.component.ts
  src/app/components/signup-page/signup-page.component.css
  src/app/components/signup-page/signup-page.component.html
  src/app/components/signup-page/signup-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#54 Fixed the overlapping of welcome text and container
  src/app/components/signup-page/signup-page.component.html
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#48 Added logout button and new route in backend
  angular.json
  backend/middlewares/authenticate.js
  backend/package.json
  backend/server.js
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
  src/app/components/login-page/login-page.component.html
  src/app/components/main-index/main-index.component.css
  src/app/components/main-index/main-index.component.html
  src/app/components/main-index/main-index.component.ts
  src/app/services/auth.service.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#72 fix api endpoints and data leaking
  angular.json
  backend/package-lock.json
  package.json
  src/app/components/signup-page/signup-page.component.ts
  src/app/services/auth.service.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#76 Make bfs canvas scrollable
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#79 Add Toaster Notifications for Form Validation on Signup
  angular.json
  backend/server.js
  package-lock.json
  package.json
  src/app/app.config.ts
  src/app/components/signup-page/signup-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#92 Revamp BFS and DFS page and removed inconsistent buttons on the page
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.css
  src/app/components/dfs-page/dfs-page.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#91 Logout Button Not Functioning Properly
  src/app/components/main-index/main-index.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#89 Add Toaster to the logging page hence improving user interactivity
  src/app/components/login-page/login-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#87 add navigation to login page on succcessful sign up
  src/app/components/signup-page/signup-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#90 Revamped Mainindex Page
  src/app/components/main-index/main-index.component.css
  src/app/components/main-index/main-index.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#97 Add logout function in main index page
  src/app/components/main-index/main-index.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#98 Add about us page and fix navbar
  src/app/app.component.ts
  src/app/app.routes.ts
  src/app/components/aboutUs-page/aboutUs.component.css
  src/app/components/aboutUs-page/aboutUs.component.html
  src/app/components/aboutUs-page/aboutUs.component.ts
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#104 Enhanced UI , Header and Footer (Lighter Shades)
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#101 Made Navbar sticky to top
  src/app/components/main-index/main-index.component.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#99 Clear graph canvas when clicked on reset BFS / DFS
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#105 Added Centralized Error Handling
  backend/server.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#107 ADD: Gitt logo to the landing page
  src/app/components/header/header.component.html
  src/app/components/header/style.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#111 Fix header styling
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.css
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/main-index/main-index.component.css
  src/app/components/main-index/main-index.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#114 Add Pass Viewer
  src/app/components/login-page/login-page.component.html
  src/app/components/login-page/login-page.component.ts
  src/app/components/signup-page/signup-page.component.html
  src/app/components/signup-page/signup-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#113 Add faq page to the application
  src/app/app.routes.ts
  src/app/components/faq/faq.component.css
  src/app/components/faq/faq.component.html
  src/app/components/faq/faq.component.spec.ts
  src/app/components/faq/faq.component.ts
  src/app/components/header/header.component.html
  src/app/components/main-index/main-index.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#115 Add dropdown to profile button on bfs and dfs page
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.css
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#127 Add Dijkstra's Algorithm and Backend IntegrationNew
  backend/models/weightedgraph.js
  backend/server.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#126 added scroll-to-top feature
  src/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#124 ADD Comman Navbar component throught the application
  src/app/app.component.ts
  src/app/components/aboutUs-page/aboutUs.component.html
  src/app/components/aboutUs-page/aboutUs.component.ts
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.css
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
  src/app/components/main-index/main-index.component.html
  src/app/components/main-index/main-index.component.ts
  src/app/components/navbar/navbar.component.css
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.spec.ts
  src/app/components/navbar/navbar.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#128 Enhance Session Security
  backend/server.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#133 Comment out import temporarily to run Server
  backend/server.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#134 Make body of bfs dfs pages consistent
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/bfs-page/bfs-page.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#137 ADD CICD Workflow for automatic assigning labels to the new created issue
  .github/workflows/autolabeler.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#142 fixed the overlapping to container and text at login interface
  src/app/components/login-page/login-page.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#148 Improve Text Clarity in Login Prompt
  .angulardoc.json
  .vscode/settings.json
  src/app/components/signup-page/signup-page.component.html
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1

#147 Add Google Login Option
  src/app/components/login-page/login-page.component.css
  src/app/components/login-page/login-page.component.html
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level2

#146 Graphanalysis
  backend/models/graphanalysis.js
  backend/server.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#151 Increase Code efficiency, Refactoring code, removing all css code lines which are unused
  src/app/components/aboutUs-page/aboutUs.component.css
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/dfs-page/dfs-page.component.css
  src/app/components/main-index/main-index.component.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#152 Added Logo Redirect to Home Page
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#153 Make Footer Interactive with Social Media Links
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#156 Added All Contributors | Issue #75
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#157 Customise the WebApp Scrollbar | Added Temp. Google Auth | Issue #117
  src/app/components/login-page/login-page.component.ts
  src/styles.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#158 Added B2T with Smooth Scrolling | Issue #116
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#161 Add "Remember me" checkbox in login form
  src/app/components/login-page/login-page.component.css
  src/app/components/login-page/login-page.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#163 added language translator
  src/app/components/header/header.component.html
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest-accepted, level3

#167 added footer contact us modal and done fixes in language translator
  src/app/components/header/header.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#170 the JWT implemented and updated .env file
  backend/.env
Labels: gssoc-ext, hacktoberfest-accepted, level1

#178 [Fix]: Updated responsive navbar feature #172
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/header/style.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#184 Added Discussion Forum
  src/app/components/header/header.component.html
  src/app/components/header/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#187 Add Interatic Quiz page
  src/app/app.routes.ts
  src/app/components/header/header.component.html
  src/app/components/navbar/navbar.component.html
  src/app/components/quiz/quiz.component.css
  src/app/components/quiz/quiz.component.html
  src/app/components/quiz/quiz.component.spec.ts
  src/app/components/quiz/quiz.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#185 Real time collaboration integrated
  backend/server.js
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#194 added chatbot issue#179 solved
  src/app/components/navbar/navbar.component.html
  src/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#192 added language translator with more languages including Indian languages
  src/app/components/header/header.component.html
  src/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#200 Newsletter Subscription Form for Website Footer
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#201 Add navbar to FAQ page
  src/app/components/faq/faq.component.html
  src/app/components/faq/faq.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#208 [Fix]: Made the signup and login forms responsive
  src/app/components/login-page/login-page.component.css
  src/app/components/signup-page/signup-page.component.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#209 Add Responsive Feedback Form to the Website
  .vscode/settings.json
  src/app/components/header/feedback.html
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#204 Added Graph Input from File Support
  backend/server.js
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#205 Added Canvas for interactive graph visualization
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#215 ADD a Feature Roadmap section
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#218 Add resouce page
  src/app/app.routes.ts
  src/app/components/header/header.component.html
  src/app/components/navbar/navbar.component.html
  src/app/components/resources/resources.component.css
  src/app/components/resources/resources.component.html
  src/app/components/resources/resources.component.spec.ts
  src/app/components/resources/resources.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#223 ADD Testing Instruction Section in README
  README.md
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#227 ADD TABLE OF CONTENT ,CHANGELOG ,TECHNICAL STACK on README file
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2

#229 ADD license and API Documentation on the README
  README.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level2

#228 Made the footer section more dynamic with animations
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#232 fix:#221/contactus
  .gitignore
  backend/package-lock.json
  backend/package.json
  backend/server.js
  src/app/app.routes.ts
  src/app/components/contact-us/contact-us.component.css
  src/app/components/contact-us/contact-us.component.html
  src/app/components/contact-us/contact-us.component.spec.ts
  src/app/components/contact-us/contact-us.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/services/auth.service.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#234 fixes:#219 Enhance footer look and information
  src/app/app.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/footer/footer.component.css
  src/app/footer/footer.component.html
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
  src/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#238 Add git contributors to the page
  src/app/app.routes.ts
  src/app/components/contributors/contributors.component.css
  src/app/components/contributors/contributors.component.html
  src/app/components/contributors/contributors.component.spec.ts
  src/app/components/contributors/contributors.component.ts
  src/app/components/header/header.component.html
  src/app/components/navbar/navbar.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#243 Added real time path trace for bfs & dfs
  src/app/components/bfs-page/bfs-page.component.css
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.css
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#246 Close dropdown when clicked anywhere on page
  src/app/components/navbar/navbar.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#248 Remove unused canvas element from footer
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1

#245 Replace default favicon
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#247 Fix typo text in footer
  src/app/footer/footer.component.html
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#251 Enhance the Introduction and ADD Diagrams/Graphics on README
  DALL·E 2024-10-16 10.59.04 - A project diagram showcasing the structure of a web application for DFS-BFS Graph Traversal. The diagram includes key components such as a user interf.webp
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#259 ADD HACKTOBERFEST AND GSSOC BANNER ON THE README
  Images/212284100-561aa473-3905-4a80-b561-0d28506553ee.gif
  Images/329829127-e79eb6de-81b1-4ffb-b6ed-f018bb977e88.png
  Images/Images
  Images/hacktober.png
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2

#253 enhanced the Hero section of the project
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#260 Fixes:#256 invisible words with white background.
  src/app/components/main-index/main-index.component.css
  src/app/components/main-index/main-index.component.html
  src/app/components/realworld/realworld.component.css
  src/app/components/resources/resources.component.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#270 Added download button in dfs/bfs pages
  src/app/components/bfs-page/bfs-page.component.html
  src/app/components/bfs-page/bfs-page.component.ts
  src/app/components/dfs-page/dfs-page.component.html
  src/app/components/dfs-page/dfs-page.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#267 Fix BFS and Dijkstra's algorithm issues
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#280 Fixes:#275 Jashwanth/Start-exploring button to signup page
  package-lock.json
  src/app/components/header/header.component.html
  src/app/footer/footer.component.css
  src/app/footer/footer.component.html
  src/app/footer/footer.component.spec.ts
  src/app/footer/footer.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#288 Fix production route and favicon
  public/favicon.ico
  src/environments/environment.prod.ts
  src/index.html
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1

#289 Add more algorithms in Master Key Graph Algorithms
  src/app/components/header/header.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#291 Re-aligned check-box
  src/app/components/login-page/login-page.component.css
  src/app/components/login-page/login-page.component.html
Labels: bug, gssoc-ext, hacktoberfest-accepted, level2

#290 Add review and questions page
  src/app/app.routes.ts
  src/app/components/header/header.component.html
  src/app/components/navbar/navbar.component.html
  src/app/components/reviews/reviews.component.css
  src/app/components/reviews/reviews.component.html
  src/app/components/reviews/reviews.component.spec.ts
  src/app/components/reviews/reviews.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#293 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yml
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#307 Fixes:#272 Jashwanth/Icon
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/img/icon.jpg
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#300 contributors page has been added.
  contributor/contributor.css
  contributor/contributor.html
  contributor/contributor.js
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#306 improve the UI of graph algo section
  src/app/components/header/header.component.html
  src/app/components/header/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#309 Fixes: #308 jashwanth/IcontoIndex
  src/app/components/navbar/navbar.component.css
  src/app/components/navbar/navbar.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#310 improve the font coloring of graph algo section.
  src/app/components/header/header.component.html
  src/app/components/header/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#313 Fixes:#302-Jashwanth/resource
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/main-index/main-index.component.html
  src/app/components/navbar/navbar.component.html
  src/app/components/resources/resources.component.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#314 Fixes: #303 - Jashwanth/faq/contributor/review
  src/app/components/contributors/contributors.component.css
  src/app/components/faq/faq.component.css
  src/app/components/faq/faq.component.html
  src/app/components/reviews/reviews.component.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#316 Fixes:#304-jashwanth/LoginPage
  src/app/components/login-page/login-page.component.css
  src/app/components/login-page/login-page.component.html
  src/app/components/login-page/login-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#317 improve UI of discussion forum.
  src/app/components/header/header.component.html
  src/app/components/header/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#323 Added user authetication with Mongodb
  backend/server.js
  src/app/components/login-page/login-page.component.html
  src/app/components/login-page/login-page.component.ts
  src/app/components/signup-page/signup-page.component.ts
  src/app/services/auth.service.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#320 Ensure BFS visualizations display correctly
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#324 Added more indian language
  src/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#327 ADD: Page404
  src/app/app.routes.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/page-not-found/page-not-found.component.css
  src/app/components/page-not-found/page-not-found.component.html
  src/app/components/page-not-found/page-not-found.component.spec.ts
  src/app/components/page-not-found/page-not-found.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#333 replaced windows alert with toast notification
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#334 modify navbar menu design
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/style.css
  src/app/components/navbar/navbar.component.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#335 Enhanced the Contributor page
  contributor/contributor.css
  contributor/contributor.html
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#339 Redesigning of Dicuss Forum with Responsiveness | Issue #318
  src/app/components/header/header.component.html
  src/app/components/header/style.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#340 Enhances the Styling in SIgnIn and SignUp Pages, also added Email Validation | Issue #73
  src/app/components/login-page/login-page.component.css
  src/app/components/login-page/login-page.component.html
  src/app/components/signup-page/signup-page.component.css
  src/app/components/signup-page/signup-page.component.html
  src/app/components/signup-page/signup-page.component.ts
Labels: enhancement, invalid, gssoc-ext, hacktoberfest-accepted, level2

#338 Redesigning of Footer and Responsiveness Addition | Issue #319
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#344 [Feature]: Add visualization
  src/app/components/header/header.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#349 Fixes:#321 After once signin redirect to home page ,
  src/app/components/signup-page/signup-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#347 Improved UI of Interactive Graph Visualizer
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted

#337 added contact us popup modal at footer - done the fixes
  src/index.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#354 Fixes: #351 - Added the small screen to select language
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#358 improve the UI of the Interactive section.
  src/app/components/header/header.component.html
  src/app/components/header/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#369 ENHNACE AND STRUCTURE THE CONTRIBUTORS SECTION
  README.md
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#370 enhanced FAQ page
  src/app/components/faq/faq.component.css
  src/app/components/faq/faq.component.html
  src/app/components/faq/faq.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#371 ADD CONTRIBUTOR GUIDE SECTION
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2

#372 Replaced all alert calls with a showToast method
  src/app/components/bfs-page/bfs-page.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#374 added ci-cd workflow
  .github/workflows/ci-cd.yaml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#363 added visualizations for dfs and dijkstra algo and buttons to display them
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#373 added functionality to discussion form
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#379 Add algo compare Page
  package.json
  src/app/app.routes.ts
  src/app/components/algocompare/algocompare.component.css
  src/app/components/algocompare/algocompare.component.html
  src/app/components/algocompare/algocompare.component.spec.ts
  src/app/components/algocompare/algocompare.component.ts
  src/app/components/navbar/navbar.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#380 Add roadmap page to the application
  src/app/components/roadmap/roadmap.component.css
  src/app/components/roadmap/roadmap.component.html
  src/app/components/roadmap/roadmap.component.spec.ts
  src/app/components/roadmap/roadmap.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#381 Add historical events Page that cover various insights about DFS/BFS
  src/app/components/history/assets/220px-Edsger_Dijkstra_1994.jpg
  src/app/components/history/assets/480px-Arthur_Cayley.jpg
  src/app/components/history/assets/Gustav-Kirchhoff-and-Robert-Bunsen.jpg
  src/app/components/history/assets/Leonhard_Euler_-_Jakob_Emanuel_Handmann_(Kunstmuseum_Basel).jpg
  src/app/components/history/assets/bfs-vs-dfs-(1).png
  src/app/components/history/history.component.css
  src/app/components/history/history.component.html
  src/app/components/history/history.component.spec.ts
  src/app/components/history/history.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#382 Add Serachable Algorithm Page
  src/app/components/algo-search/algo-search.component.css
  src/app/components/algo-search/algo-search.component.html
  src/app/components/algo-search/algo-search.component.spec.ts
  src/app/components/algo-search/algo-search.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#383 Add Profile Page to the application
  package-lock.json
  package.json
  src/app/app.routes.ts
  src/app/components/profile/profile.component.css
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.spec.ts
  src/app/components/profile/profile.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#388 Github actions for more connectivity!
  .github/workflows/greetings.yml
  .github/workflows/issue_open_close.yml
  .github/workflows/pr-merged.yaml
  .github/workflows/pr_raise.yml
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#389 added directed graph page
  src/app/components/Graphs/directedgraph.html
  src/app/components/header/header.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#390 added undirected graph page
  src/app/components/Graphs/undirectedgraph.html
  src/app/components/header/header.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted

#399 Improved login/signup page matching sites UI
  src/app/components/login-page/login-page.component.css
  src/app/components/login-page/login-page.component.html
  src/app/components/signup-page/signup-page.component.css
  src/app/components/signup-page/signup-page.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#400 enhanced the footer added transitions and effects #169
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#401 Created the Testimonials section
  src/index.html
  src/styles.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#415 Update README.md added Stargazers and Forkers section to readme.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#420 added weighted graph visualizer page
  src/app/components/Graphs/weightedgraph.html
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#421 Added Question Section for BFS and DFS algorithms
  src/app/components/quiz/quiz.component.css
Labels: gssoc-ext, hacktoberfest-accepted

#422 added tree visualization page
  src/app/components/Graphs/tree.html
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#424 "Added Logo and Configure Navbar for Enhanced Branding"
  a.png
  b.png
  backend/package-lock.json
  c.png
  d.png
  e.png
  f.png
  package-lock.json
  public/a.png
  public/b.png
  public/c.png
  public/d.png
  public/e.png
  public/f.png
  src/app/app.routes.ts
  src/app/components/header/header.component.html
  src/app/components/header/img/a.png
  src/app/components/header/img/b.png
  src/app/components/header/img/c.png
  src/app/components/header/img/d.png
  src/app/components/header/img/e.png
  src/app/components/header/img/f.png
  src/app/components/navbar/navbar.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#429 automated python project structure
  .github/scripts/generate_structure.py
  .github/workflows/update-structure.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#443 Create LICENSE
  LICENSE
Labels: gssoc-ext, hacktoberfest-accepted

#432 solved #376 Added 3 categories of quizess (esay,med,difficult)
  src/app/app.routes.ts
  src/app/components/header/header.component.html
  src/app/components/quiz/quiz.component.css
  src/app/components/quiz/quiz.component.html
  src/app/components/quiz/quiz.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2
