Repository sakeel-103/DFS-BFS-Graph-Travers, pull requests merged in 2024-11, with the labels that each got.

#507 Implemented a stop button for BFS/ DFS/ Dijksra visualization
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#508 Improve User Interaction with Hover Effects in GraphExplorer Pro
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#509 Enhance-Visual Appearance of Contact-Us page in contact.html and contact.css with add icons and input field in text field of input.
  src/contact.css
  src/contact.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#510 Added Logo
  src/app/components/navbar/a.png
  src/app/components/navbar/navbar.component.html
Labels: gssoc-ext, hacktoberfest-accepted

#517 Added Real world applications under different categories !!
  src/app/components/realworld/realworld.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#519 CREATE CUSTOM ISSUE TEMPLATE
  .github/ISSUE_TEMPLATE/custom.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#520 CREATE Q&A Suggestion Template
  .github/ISSUE_TEMPLATE/Config.yml
Labels: gssoc-ext, hacktoberfest-accepted

#521 Enhanced Newsletter Subscription Experience
  src/app/components/realworld/realworld.component.css
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1

#524 add chatbot gemini
  src/app/app.routes.ts
  src/app/components/geminibot/geminibot.component.css
  src/app/components/geminibot/geminibot.component.html
  src/app/components/geminibot/geminibot.component.spec.ts
  src/app/components/geminibot/geminibot.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#527 Enhance footer design
  src/app/app.module.ts
  src/app/components/contact-us/contact-us/contact.us/contact-us.component.css
  src/app/components/contact-us/contact-us/contact.us/contact-us.component.html
  src/app/components/contact-us/contact-us/contact.us/contact-us.component.ts
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#528 Enhance the Practice Questions Page | Issue #499
  src/app/components/practice/practice.component.css
  src/app/components/practice/practice.component.html
  src/app/components/practice/practice.component.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#533 Enhance the Resources Page, Added the YT Data Fetch by API, Added Fiter by Author/Creators | Issuee #506
  package.json
  src/app/components/resources/resources.component.css
  src/app/components/resources/resources.component.html
  src/app/components/resources/resources.component.ts
  src/environments/environment.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#535 Enhance the Text Editor UI , Added Themes, Added Multi Programming and Scripting Languages | Issue #505
  src/app/components/code-editor/code-editor.component.css
  src/app/components/code-editor/code-editor.component.html
  src/app/components/code-editor/code-editor.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#526 Integrated NQueen Visualizer | Issue #498
  src/app/app.module.ts
  src/app/app.routes.ts
  src/app/components/n-queen-visualizer/n-queen-visualizer.component.css
  src/app/components/n-queen-visualizer/n-queen-visualizer.component.html
  src/app/components/n-queen-visualizer/n-queen-visualizer.component.spec.ts
  src/app/components/n-queen-visualizer/n-queen-visualizer.component.ts
  src/app/components/navbar/navbar.component.html
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#529 Make Footer Styled
  src/contact.css
  src/contact.html
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#538 fix issue 446
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
  src/app/components/header/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#541 Enhance the FAQs UI | Added Search Bar | Added Toggler | Issue #504
  src/app/components/faq/faq.component.css
  src/app/components/faq/faq.component.html
  src/app/components/faq/faq.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1

#544 Add Visual Stack and Queue Displays using Dfs adn Bfs
  package-lock.json
  src/app/app.routes.ts
  src/app/components/visual-stack-queue/visual-stack-queue.component.css
  src/app/components/visual-stack-queue/visual-stack-queue.component.html
  src/app/components/visual-stack-queue/visual-stack-queue.component.spec.ts
  src/app/components/visual-stack-queue/visual-stack-queue.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#547 Resolved duplicate buttons
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted

#548 Added Google Sign In method in frontend using gapi
  angular.json
  backend/server.js
  netlify.toml
  src/app/components/login-page/login-page.component.html
  src/app/components/login-page/login-page.component.ts
  src/app/services/auth.service.ts
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#552 Add maze runner game
  src/app/app.routes.ts
  src/app/components/maze-runner-visualizer/maze-runner-visualizer.component.css
  src/app/components/maze-runner-visualizer/maze-runner-visualizer.component.html
  src/app/components/maze-runner-visualizer/maze-runner-visualizer.component.spec.ts
  src/app/components/maze-runner-visualizer/maze-runner-visualizer.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2

#555 Added feedback form in frontend & backend model + query to store/view the same
  .github/scripts/generate_structure.py
  .github/workflows/autolabeler.yml
  .github/workflows/pr-checker.yml
  .github/workflows/update-structure.yml
  Images/Images
  backend/models/Feedback.js
  backend/server.js
  src/app/app.routes.ts
  src/app/components/feedback/feedback.component.css
  src/app/components/feedback/feedback.component.html
  src/app/components/feedback/feedback.component.spec.ts
  src/app/components/feedback/feedback.component.ts
  src/app/components/header/header.component.html
  src/app/components/navbar/navbar.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level3

#539 Improve UI and fetch GitHub data for stats and contributors
  contributor/contributor.css
  contributor/contributor.html
  contributor/contributor.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#553 Add tresure hunt game for better understanding of dfs and bfs
  src/app/app.routes.ts
  src/app/components/treasure-hunt-visualizer/treasure-hunt-visualizer.component.css
  src/app/components/treasure-hunt-visualizer/treasure-hunt-visualizer.component.html
  src/app/components/treasure-hunt-visualizer/treasure-hunt-visualizer.component.spec.ts
  src/app/components/treasure-hunt-visualizer/treasure-hunt-visualizer.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level3

#556 SORTING VISUALIZER OF ALL THE SORTIGN ALGORITHEM
  src/app/app.routes.ts
  src/app/components/header/header.component.html
  src/app/components/sorting-v/sorting.component.css
  src/app/components/sorting-v/sorting.component.html
  src/app/components/sorting-v/sorting.component.spec.ts
  src/app/components/sorting-v/sorting.component.ts
  src/app/components/sorting-v/style.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#559 Add robot navigation game
  src/app/components/robot/robot.component.css
  src/app/components/robot/robot.component.html
  src/app/components/robot/robot.component.spec.ts
  src/app/components/robot/robot.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#575 fix feedback url
  src/app/components/feedback/feedback.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#576 Enhanced UI with inline hover effects, color changes, and shadow transitions for resource and video cards.
  src/app/components/resources/resources.component.css
  src/app/components/resources/resources.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#579 Added More Unique Graph-Related Questions to Question Bank
  src/app/components/practice/practice.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#580 Enhancing User Experience with Interactive Design and Colorful UI Updates
  src/app/components/practice/practice.component.css
  src/app/components/practice/practice.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#581 Adding hovering effects to the navabr elements !!
  src/app/components/header/header.component.css
  src/app/components/header/header.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#582 Adding Support for Additional Languages in Code Editor
  src/app/components/code-editor/code-editor.component.html
  src/app/components/code-editor/code-editor.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#583 Enhance UI with Blue and White Shades for a Modern, Clean Look For Reviews page !!!
  src/app/components/reviews/reviews.component.css
  src/app/components/reviews/reviews.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#558 Add Tower Traverser gamefication view to the application
  src/app/components/tower-traverser-visualizer/tower-traverser-visualizer.component.css
  src/app/components/tower-traverser-visualizer/tower-traverser-visualizer.component.html
  src/app/components/tower-traverser-visualizer/tower-traverser-visualizer.component.spec.ts
  src/app/components/tower-traverser-visualizer/tower-traverser-visualizer.component.ts
  src/app/components/treasure-hunt-visualizer/treasure-hunt-visualizer.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#560 Add forest game to the application
  src/app/app.routes.ts
  src/app/components/forest-explorer/forest-explorer.component.css
  src/app/components/forest-explorer/forest-explorer.component.html
  src/app/components/forest-explorer/forest-explorer.component.spec.ts
  src/app/components/forest-explorer/forest-explorer.component.ts
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#584 FEATURE: Addition of Algo Compare Page #554
  src/app/app.routes.ts
  src/app/components/compare/compare.component.css
  src/app/components/compare/compare.component.html
  src/app/components/compare/compare.component.spec.ts
  src/app/components/compare/compare.component.ts
  src/app/components/navbar/navbar.component.html
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#595 Improve total contributors page done ! #587 🟢
  contributor/contributor.html
  contributor/contributor.js
  contributor/contributors.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#596 Add a User Profiles page done ! #588 🌟🌟🌟
  src/index.html
  src/styles.css
  src/testp.css
  src/testp.html
  src/testp.js
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#597 Add trailing dots cursor effect for Enhanced User Experience done ! #590 🌟🌟
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#600 Add a pop up dialog box for subscribing to newsletter done ! #591 ✨✨
  newsletterpopup.jpg
  src/index.html
  src/newsletterpopup.js
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#601 Add a pop up dialog box for Polls/Survey done ! #592 🌟🌟
  src/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#605 Add Edit Profile Feature in Profile Page done ! #602 🟢🟢
  src/index.html
  src/profileedit.html
  src/testp.html
  src/testp.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#608 #549: dark mode
  src/app/components/header/header.component.html
  src/app/components/header/script.js
  src/app/components/header/style.css
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest
